{
    "songs" = [
        {
            "name": "Happy Birthday",
            "notes": [
                { "note": "C4", "duration": 500 },
                { "note": "C4", "duration": 250 },
                { "note": "D4", "duration": 750 },
                { "note": "C4", "duration": 750 },
                { "note": "F4", "duration": 750 },
                { "note": "E4", "duration": 1500 },
                { "note": "C4", "duration": 500 },
                { "note": "C4", "duration": 250 },
                { "note": "D4", "duration": 750 },
                { "note": "C4", "duration": 750 },
                { "note": "G4", "duration": 750 },
                { "note": "F4", "duration": 1500 }
            ]
        },
        {
            "name": "Twinkle Twinkle Little Star",
            "notes": [
                { "note": "C4", "duration": 500 },
                { "note": "C4", "duration": 500 },
                { "note": "G4", "duration": 500 },
                { "note": "G4", "duration": 500 },
                { "note": "A4", "duration": 500 },
                { "note": "A4", "duration": 500 },
                { "note": "G4", "duration": 1000 },
                { "note": "F4", "duration": 500 },
                { "note": "F4", "duration": 500 },
                { "note": "E4", "duration": 500 },
                { "note": "E4", "duration": 500 },
                { "note": "D4", "duration": 500 },
                { "note": "D4", "duration": 500 },
                { "note": "C4", "duration": 1000 }
            ]
        },
        {
            "name": "City so loud - wasted",
            "notes": [
                { "note": "E4", "duration": 500 },
                { "note": "D4", "duration": 500 },
                { "note": "C4", "duration": 500 },
                { "note": "D4", "duration": 500 },
                { "note": "E4", "duration": 500 },
                { "note": "E4", "duration": 500 },
                { "note": "E4", "duration": 1000 },
                { "note": "D4", "duration": 500 },
                { "note": "D4", "duration": 500 },
                { "note": "D4", "duration": 1000 },
                { "note": "E4", "duration": 500 },
                { "note": "G4", "duration": 500 },
                { "note": "G4", "duration": 1000 }
            ]
        },
        {
            "name": "For World - Extended",
            "notes": [
                { "note": "E5", "duration": 500 },
                { "note": "Eb5", "duration": 150 },
                { "note": "E5", "duration": 150 },
                { "note": "Eb5", "duration": 150 },
                { "note": "E5", "duration": 150 },
                { "note": "B4", "duration": 150 },
                { "note": "D5", "duration": 150 },
                { "note": "C5", "duration": 150 },
                { "note": "A4", "duration": 250 },
                { "note": "C4", "duration": 150 },
                { "note": "E4", "duration": 150 },
                { "note": "A4", "duration": 150 },
                { "note": "B4", "duration": 250 },
                { "note": "E4", "duration": 150 },
                { "note": "Ab4", "duration": 150 },
                { "note": "B4", "duration": 150 },
                { "note": "C5", "duration": 250 },

                { "note": "E5", "duration": 150 },
                { "note": "Eb5", "duration": 150 },
                { "note": "E5", "duration": 150 },
                { "note": "Eb5", "duration": 150 },
                { "note": "E5", "duration": 150 },
                { "note": "B4", "duration": 150 },
                { "note": "D5", "duration": 150 },
                { "note": "C5", "duration": 150 },
                { "note": "A4", "duration": 250 },
                { "note": "C4", "duration": 150 },
                { "note": "E4", "duration": 150 },
                { "note": "A4", "duration": 150 },
                { "note": "B4", "duration": 250 },
                { "note": "E4", "duration": 150 },
                { "note": "C5", "duration": 150 },
                { "note": "B4", "duration": 150 },
                { "note": "A4", "duration": 500 },

                { "note": "A4", "duration": 250 },
                { "note": "C4", "duration": 150 },
                { "note": "E4", "duration": 150 },
                { "note": "A4", "duration": 150 },
                { "note": "B4", "duration": 250 },
                { "note": "E4", "duration": 150 },
                { "note": "Ab4", "duration": 150 },
                { "note": "B4", "duration": 150 },
                { "note": "C5", "duration": 250 },

                { "note": "E5", "duration": 150 },
                { "note": "Eb5", "duration": 150 },
                { "note": "E5", "duration": 150 },
                { "note": "Eb5", "duration": 150 },
                { "note": "E5", "duration": 150 },
                { "note": "B4", "duration": 150 },
                { "note": "D5", "duration": 150 },
                { "note": "C5", "duration": 150 },
                { "note": "A4", "duration": 250 },
                { "note": "C4", "duration": 150 },
                { "note": "E4", "duration": 150 },
                { "note": "A4", "duration": 150 },
                { "note": "B4", "duration": 250 },
                { "note": "E4", "duration": 150 },
                { "note": "C5", "duration": 150 },
                { "note": "B4", "duration": 150 },
                { "note": "A4", "duration": 100 },

                { "note": "A4", "duration": 250 },
                { "note": "C4", "duration": 150 },
                { "note": "E4", "duration": 150 },
                { "note": "A4", "duration": 150 },
                { "note": "B4", "duration": 250 },
                { "note": "E4", "duration": 150 },
                { "note": "Ab4", "duration": 150 },
                { "note": "B4", "duration": 150 },
                { "note": "C5", "duration": 250 },

                { "note": "E5", "duration": 150 },
                { "note": "Eb5", "duration": 150 },
                { "note": "E5", "duration": 150 },
                { "note": "Eb5", "duration": 150 },
                { "note": "E5", "duration": 150 },
                { "note": "B4", "duration": 150 },
                { "note": "D5", "duration": 150 },
                { "note": "C5", "duration": 150 },
                { "note": "A4", "duration": 250 },
                { "note": "C4", "duration": 150 },
                { "note": "E4", "duration": 150 },
                { "note": "A4", "duration": 150 },
                { "note": "B4", "duration": 250 },
                { "note": "E4", "duration": 150 },
                { "note": "C5", "duration": 150 },
                { "note": "B4", "duration": 150 },
                { "note": "A4", "duration": 1200 }
            ]
        },
        {
            "name": "Canon in D - Main Theme",
            "notes": [
                { "note": "D3", "duration": 1000 },
                { "note": "A2", "duration": 1000 },
                { "note": "B2", "duration": 1000 },
                { "note": "Gb2", "duration": 1000 },
                { "note": "G2", "duration": 1000 },
                { "note": "D2", "duration": 1000 },
                { "note": "G2", "duration": 1000 },
                { "note": "A2", "duration": 1000 },

                { "note": "D4", "duration": 500 },
                { "note": "Gb4", "duration": 500 },
                { "note": "A4", "duration": 500 },
                { "note": "G4", "duration": 500 },
                { "note": "Gb4", "duration": 500 },
                { "note": "D4", "duration": 500 },
                { "note": "E4", "duration": 500 },
                { "note": "Gb4", "duration": 500 },
                { "note": "G4", "duration": 500 },
                { "note": "A4", "duration": 500 },
                { "note": "B4", "duration": 500 },
                { "note": "A4", "duration": 500 },
                { "note": "G4", "duration": 500 },
                { "note": "Gb4", "duration": 500 },
                { "note": "G4", "duration": 500 },
                { "note": "A4", "duration": 500 },
                { "note": "D5", "duration": 500 },
                { "note": "C5", "duration": 500 },
                { "note": "B4", "duration": 500 },
                { "note": "A4", "duration": 500 },
                { "note": "B4", "duration": 500 },
                { "note": "C5", "duration": 500 },
                { "note": "B4", "duration": 500 },
                { "note": "A4", "duration": 500 },
                { "note": "G4", "duration": 1000 },
                { "note": "A4", "duration": 1000 }
            ]
        },
        {
            "name": "Moonlight soneta - First Love",
            "notes": [
                { "note": "Gb2", "duration": 600 },
                { "note": "Bb2", "duration": 600 },
                { "note": "Db3", "duration": 600 },
                { "note": "Gb3", "duration": 600 },
                { "note": "Bb3", "duration": 600 },
                { "note": "Db4", "duration": 600 },
                { "note": "Bb3", "duration": 600 },
                { "note": "Db4", "duration": 600 },
                { "note": "Gb2", "duration": 600 },
                { "note": "Bb2", "duration": 600 },
                { "note": "Db3", "duration": 600 },
                { "note": "Gb3", "duration": 600 },
                { "note": "Bb3", "duration": 600 },
                { "note": "Db4", "duration": 600 },
                { "note": "Bb3", "duration": 600 },
                { "note": "Db4", "duration": 600 },

                { "note": "G2", "duration": 600 },
                { "note": "B2", "duration": 600 },
                { "note": "D3", "duration": 600 },
                { "note": "G3", "duration": 600 },
                { "note": "B3", "duration": 600 },
                { "note": "D4", "duration": 600 },
                { "note": "B3", "duration": 600 },
                { "note": "D4", "duration": 600 },
                { "note": "Ab2", "duration": 600 },
                { "note": "C3", "duration": 600 },
                { "note": "Eb3", "duration": 600 },
                { "note": "Ab3", "duration": 600 },
                { "note": "C4", "duration": 600 },
                { "note": "Eb4", "duration": 600 },
                { "note": "C4", "duration": 600 },
                { "note": "Eb4", "duration": 600 },

                { "note": "Gb4", "duration": 1200 },
                { "note": "F4", "duration": 1200 },
                { "note": "E4", "duration": 1200 },
                { "note": "Eb4", "duration": 1200 }
            ]
        },
        {
            "name": "The Entertainer (Scott Joplin) - Ragtime",
            "notes": [
                { "note": "D4", "duration": 250 },
                { "note": "Eb4", "duration": 250 },
                { "note": "E4", "duration": 500 },
                { "note": "C5", "duration": 250 },
                { "note": "E4", "duration": 500 },
                { "note": "C5", "duration": 250 },
                { "note": "E4", "duration": 750 },
                { "note": "C5", "duration": 250 },
                { "note": "D4", "duration": 250 },
                { "note": "Eb4", "duration": 250 },
                { "note": "E4", "duration": 500 },
                { "note": "C5", "duration": 250 },
                { "note": "E4", "duration": 500 },
                { "note": "C5", "duration": 250 },
                { "note": "E4", "duration": 750 },
                { "note": "C5", "duration": 250 },

                { "note": "D4", "duration": 250 },
                { "note": "Eb4", "duration": 250 },
                { "note": "E4", "duration": 250 },
                { "note": "C5", "duration": 250 },
                { "note": "E4", "duration": 250 },
                { "note": "C5", "duration": 250 },
                { "note": "E4", "duration": 250 },
                { "note": "Bb4", "duration": 250 },
                { "note": "A4", "duration": 250 },
                { "note": "G4", "duration": 250 },
                { "note": "Gb4", "duration": 250 },
                { "note": "A4", "duration": 250 },
                { "note": "C5", "duration": 500 },
                { "note": "E5", "duration": 250 },
                { "note": "D5", "duration": 250 },
                { "note": "C5", "duration": 250 },
                { "note": "A4", "duration": 250 },
                { "note": "D4", "duration": 250 },
                { "note": "Eb4", "duration": 250 },
                { "note": "E4", "duration": 250 },
                { "note": "C5", "duration": 250 },
                { "note": "E4", "duration": 250 },
                { "note": "C5", "duration": 250 },
                { "note": "E4", "duration": 250 },
                { "note": "Bb4", "duration": 250 },
                { "note": "A4", "duration": 250 },
                { "note": "G4", "duration": 250 },
                { "note": "Gb4", "duration": 250 },
                { "note": "A4", "duration": 250 },
                { "note": "C5", "duration": 1000 }
            ]
        },
        {
            "name": "Turkish March (Mozart) - Complete Version",
            "notes": [
                { "note": "B4", "duration": 300 },
                { "note": "A4", "duration": 300 },
                { "note": "Ab4", "duration": 300 },
                { "note": "A4", "duration": 300 },
                { "note": "C5", "duration": 600 },
                { "note": "D5", "duration": 300 },
                { "note": "C5", "duration": 300 },
                { "note": "B4", "duration": 300 },
                { "note": "C5", "duration": 300 },
                { "note": "Eb5", "duration": 600 },

                { "note": "F5", "duration": 300 },
                { "note": "Eb5", "duration": 300 },
                { "note": "D5", "duration": 300 },
                { "note": "Eb5", "duration": 300 },
                { "note": "F5", "duration": 600 },
                { "note": "G5", "duration": 300 },
                { "note": "F5", "duration": 300 },
                { "note": "Eb5", "duration": 300 },
                { "note": "D5", "duration": 300 },
                { "note": "C5", "duration": 1200 },

                { "note": "B4", "duration": 300 },
                { "note": "A4", "duration": 300 },
                { "note": "Ab4", "duration": 300 },
                { "note": "A4", "duration": 300 },
                { "note": "C5", "duration": 600 },
                { "note": "D5", "duration": 300 },
                { "note": "C5", "duration": 300 },
                { "note": "B4", "duration": 300 },
                { "note": "A4", "duration": 300 },
                { "note": "B4", "duration": 1200 },

                { "note": "B4", "duration": 200 },
                { "note": "C5", "duration": 200 },
                { "note": "B4", "duration": 200 },
                { "note": "A4", "duration": 300 },
                { "note": "Ab4", "duration": 200 },
                { "note": "A4", "duration": 200 },
                { "note": "B4", "duration": 200 },
                { "note": "C5", "duration": 600 },

                { "note": "D5", "duration": 200 },
                { "note": "Eb5", "duration": 200 },
                { "note": "D5", "duration": 200 },
                { "note": "C5", "duration": 300 },
                { "note": "B4", "duration": 200 },
                { "note": "C5", "duration": 200 },
                { "note": "D5", "duration": 200 },
                { "note": "Eb5", "duration": 600 },

                { "note": "F5", "duration": 150 },
                { "note": "G5", "duration": 150 },
                { "note": "F5", "duration": 150 },
                { "note": "Eb5", "duration": 150 },
                { "note": "D5", "duration": 150 },
                { "note": "C5", "duration": 150 },
                { "note": "B4", "duration": 150 },
                { "note": "A4", "duration": 150 },
                { "note": "B4", "duration": 150 },
                { "note": "C5", "duration": 150 },
                { "note": "D5", "duration": 150 },
                { "note": "Eb5", "duration": 150 },
                { "note": "F5", "duration": 600 },

                { "note": "F4", "duration": 400 },
                { "note": "G4", "duration": 400 },
                { "note": "Ab4", "duration": 400 },
                { "note": "Bb4", "duration": 400 },
                { "note": "C5", "duration": 800 },

                { "note": "Db5", "duration": 300 },
                { "note": "C5", "duration": 300 },
                { "note": "Bb4", "duration": 300 },
                { "note": "Ab4", "duration": 300 },
                { "note": "G4", "duration": 300 },
                { "note": "F4", "duration": 300 },
                { "note": "Eb4", "duration": 300 },
                { "note": "F4", "duration": 300 },
                { "note": "G4", "duration": 600 },

                { "note": "Ab4", "duration": 200 },
                { "note": "G4", "duration": 200 },
                { "note": "Gb4", "duration": 200 },
                { "note": "F4", "duration": 200 },
                { "note": "E4", "duration": 200 },
                { "note": "Eb4", "duration": 200 },
                { "note": "D4", "duration": 200 },
                { "note": "Db4", "duration": 200 },
                { "note": "C4", "duration": 400 },

                { "note": "C5", "duration": 200 },
                { "note": "D5", "duration": 200 },
                { "note": "Eb5", "duration": 200 },
                { "note": "F5", "duration": 200 },
                { "note": "G5", "duration": 300 },
                { "note": "Ab5", "duration": 300 },
                { "note": "G5", "duration": 300 },
                { "note": "F5", "duration": 300 },

                { "note": "Eb5", "duration": 150 },
                { "note": "D5", "duration": 150 },
                { "note": "C5", "duration": 150 },
                { "note": "B4", "duration": 150 },
                { "note": "A4", "duration": 150 },
                { "note": "G4", "duration": 150 },
                { "note": "F4", "duration": 150 },
                { "note": "E4", "duration": 150 },
                { "note": "F4", "duration": 150 },
                { "note": "G4", "duration": 150 },
                { "note": "A4", "duration": 150 },
                { "note": "B4", "duration": 150 },
                { "note": "C5", "duration": 600 },

                { "note": "B4", "duration": 250 },
                { "note": "A4", "duration": 250 },
                { "note": "Ab4", "duration": 250 },
                { "note": "A4", "duration": 250 },
                { "note": "C5", "duration": 500 },

                { "note": "B4", "duration": 100 },
                { "note": "C5", "duration": 100 },
                { "note": "D5", "duration": 300 },
                { "note": "C5", "duration": 250 },
                { "note": "B4", "duration": 250 },
                { "note": "C5", "duration": 250 },
                { "note": "Eb5", "duration": 500 },

                { "note": "D5", "duration": 100 },
                { "note": "Eb5", "duration": 100 },
                { "note": "F5", "duration": 300 },
                { "note": "Eb5", "duration": 250 },
                { "note": "D5", "duration": 250 },
                { "note": "Eb5", "duration": 250 },
                { "note": "F5", "duration": 500 },

                { "note": "G5", "duration": 100 },
                { "note": "F5", "duration": 100 },
                { "note": "Eb5", "duration": 100 },
                { "note": "D5", "duration": 100 },
                { "note": "C5", "duration": 100 },
                { "note": "B4", "duration": 100 },
                { "note": "A4", "duration": 100 },
                { "note": "B4", "duration": 100 },
                { "note": "C5", "duration": 100 },
                { "note": "D5", "duration": 100 },
                { "note": "Eb5", "duration": 100 },
                { "note": "F5", "duration": 100 },
                { "note": "G5", "duration": 100 },
                { "note": "Ab5", "duration": 100 },
                { "note": "G5", "duration": 100 },
                { "note": "F5", "duration": 100 },

                { "note": "Eb5", "duration": 100 },
                { "note": "D5", "duration": 100 },
                { "note": "C5", "duration": 100 },
                { "note": "B4", "duration": 100 },
                { "note": "A4", "duration": 100 },
                { "note": "G4", "duration": 100 },
                { "note": "F4", "duration": 100 },
                { "note": "G4", "duration": 100 },
                { "note": "A4", "duration": 100 },
                { "note": "B4", "duration": 100 },
                { "note": "C5", "duration": 100 },
                { "note": "D5", "duration": 100 },
                { "note": "Eb5", "duration": 100 },
                { "note": "F5", "duration": 100 },
                { "note": "G5", "duration": 100 },
                { "note": "F5", "duration": 100 },

                { "note": "Eb5", "duration": 200 },
                { "note": "D5", "duration": 200 },
                { "note": "C5", "duration": 200 },
                { "note": "B4", "duration": 200 },
                { "note": "A4", "duration": 400 },
                { "note": "B4", "duration": 400 },
                { "note": "C5", "duration": 800 },

                { "note": "F5", "duration": 150 },
                { "note": "Eb5", "duration": 150 },
                { "note": "D5", "duration": 150 },
                { "note": "C5", "duration": 150 },
                { "note": "B4", "duration": 150 },
                { "note": "A4", "duration": 150 },
                { "note": "G4", "duration": 150 },
                { "note": "F4", "duration": 150 },

                { "note": "G4", "duration": 300 },
                { "note": "A4", "duration": 300 },
                { "note": "B4", "duration": 300 },
                { "note": "C5", "duration": 600 },
                { "note": "D5", "duration": 300 },
                { "note": "Eb5", "duration": 300 },
                { "note": "F5", "duration": 600 },

                { "note": "G5", "duration": 400 },
                { "note": "F5", "duration": 400 },
                { "note": "Eb5", "duration": 400 },
                { "note": "D5", "duration": 400 },
                { "note": "C5", "duration": 800 },

                { "note": "F5", "duration": 300 },
                { "note": "Eb5", "duration": 300 },
                { "note": "D5", "duration": 300 },
                { "note": "C5", "duration": 300 },
                { "note": "B4", "duration": 300 },
                { "note": "A4", "duration": 300 },
                { "note": "B4", "duration": 600 },
                { "note": "C5", "duration": 1200 },

                { "note": "C5", "duration": 200 },
                { "note": "D5", "duration": 200 },
                { "note": "Eb5", "duration": 200 },
                { "note": "F5", "duration": 200 },
                { "note": "G5", "duration": 200 },
                { "note": "F5", "duration": 200 },
                { "note": "Eb5", "duration": 200 },
                { "note": "D5", "duration": 200 },
                { "note": "C5", "duration": 1600 }
            ]
        },
        {
            "name": "Drain with the train",
            "notes": [
                { "note": "Eb4", "duration": 800 },
                { "note": "F4", "duration": 400 },
                { "note": "G4", "duration": 800 },
                { "note": "F4", "duration": 400 },
                { "note": "Eb4", "duration": 1200 },
                { "note": "Bb3", "duration": 800 },
                { "note": "C4", "duration": 400 },
                { "note": "D4", "duration": 800 },
                { "note": "C4", "duration": 400 },
                { "note": "Bb3", "duration": 1200 },

                { "note": "F3", "duration": 800 },
                { "note": "G3", "duration": 400 },
                { "note": "Ab3", "duration": 800 },
                { "note": "G3", "duration": 400 },
                { "note": "F3", "duration": 1200 },
                { "note": "Eb3", "duration": 800 },
                { "note": "F3", "duration": 400 },
                { "note": "G3", "duration": 800 },
                { "note": "Ab3", "duration": 400 },
                { "note": "Bb3", "duration": 1600 },

                { "note": "C4", "duration": 600 },
                { "note": "D4", "duration": 600 },
                { "note": "Eb4", "duration": 600 },
                { "note": "F4", "duration": 600 },
                { "note": "G4", "duration": 800 },
                { "note": "Ab4", "duration": 800 },
                { "note": "Bb4", "duration": 1200 },

                { "note": "Ab4", "duration": 800 },
                { "note": "G4", "duration": 800 },
                { "note": "F4", "duration": 800 },
                { "note": "Eb4", "duration": 800 },
                { "note": "D4", "duration": 800 },
                { "note": "C4", "duration": 1600 }
            ]
        },
        {
            "name": "Wait for me",
            "notes": [
                { "note": "Ab4", "duration": 150 },
                { "note": "Bb4", "duration": 150 },
                { "note": "C5", "duration": 150 },
                { "note": "Db5", "duration": 300 },
                { "note": "C5", "duration": 300 },
                { "note": "Bb4", "duration": 150 },
                { "note": "Ab4", "duration": 150 },
                { "note": "G4", "duration": 150 },
                { "note": "Ab4", "duration": 450 },
                { "note": "Eb4", "duration": 150 },
                { "note": "F4", "duration": 150 },
                { "note": "G4", "duration": 150 },
                { "note": "Ab4", "duration": 300 },
                { "note": "G4", "duration": 300 },
                { "note": "F4", "duration": 150 },
                { "note": "Eb4", "duration": 150 },
                { "note": "D4", "duration": 150 },
                { "note": "Eb4", "duration": 450 },
                { "note": "F4", "duration": 100 },
                { "note": "Gb4", "duration": 100 },
                { "note": "G4", "duration": 100 },
                { "note": "Ab4", "duration": 100 },
                { "note": "A4", "duration": 100 },
                { "note": "Bb4", "duration": 100 },
                { "note": "B4", "duration": 100 },
                { "note": "C5", "duration": 100 },
                { "note": "Db5", "duration": 100 },
                { "note": "D5", "duration": 100 },
                { "note": "Eb5", "duration": 100 },
                { "note": "E5", "duration": 100 },
                { "note": "F5", "duration": 300 },
                { "note": "Eb5", "duration": 150 },
                { "note": "Db5", "duration": 150 },
                { "note": "C5", "duration": 150 },
                { "note": "Bb4", "duration": 150 },
                { "note": "Ab4", "duration": 150 },
                { "note": "G4", "duration": 150 },
                { "note": "F4", "duration": 150 },
                { "note": "Eb4", "duration": 150 },
                { "note": "Ab4", "duration": 900 }
            ]
        },
        {
            "name": "Rain",
            "notes": [
                { "note": "A3", "duration": 400 },
                { "note": "E4", "duration": 400 },
                { "note": "A4", "duration": 400 },
                { "note": "C5", "duration": 400 },
                { "note": "E5", "duration": 800 },

                { "note": "F3", "duration": 400 },
                { "note": "A3", "duration": 400 },
                { "note": "C4", "duration": 400 },
                { "note": "F4", "duration": 400 },
                { "note": "A4", "duration": 800 },

                { "note": "C3", "duration": 400 },
                { "note": "G3", "duration": 400 },
                { "note": "C4", "duration": 400 },
                { "note": "E4", "duration": 400 },
                { "note": "G4", "duration": 800 },

                { "note": "G3", "duration": 400 },
                { "note": "B3", "duration": 400 },
                { "note": "D4", "duration": 400 },
                { "note": "G4", "duration": 400 },
                { "note": "B4", "duration": 800 },

                { "note": "E5", "duration": 600 },
                { "note": "D5", "duration": 300 },
                { "note": "C5", "duration": 300 },
                { "note": "B4", "duration": 600 },
                { "note": "A4", "duration": 600 },

                { "note": "A2", "duration": 400 },
                { "note": "E3", "duration": 400 },
                { "note": "A3", "duration": 400 },

                { "note": "C5", "duration": 600 },
                { "note": "B4", "duration": 300 },
                { "note": "A4", "duration": 300 },
                { "note": "G4", "duration": 600 },
                { "note": "F4", "duration": 600 },

                { "note": "F2", "duration": 400 },
                { "note": "A2", "duration": 400 },
                { "note": "C3", "duration": 400 },

                { "note": "A4", "duration": 600 },
                { "note": "G4", "duration": 300 },
                { "note": "F4", "duration": 300 },
                { "note": "E4", "duration": 600 },
                { "note": "D4", "duration": 600 },

                { "note": "C2", "duration": 400 },
                { "note": "G2", "duration": 400 },
                { "note": "C3", "duration": 400 },

                { "note": "F4", "duration": 600 },
                { "note": "E4", "duration": 300 },
                { "note": "D4", "duration": 300 },
                { "note": "C4", "duration": 1200 },

                { "note": "G2", "duration": 400 },
                { "note": "B2", "duration": 400 },
                { "note": "D3", "duration": 400 },

                { "note": "D4", "duration": 100 },
                { "note": "E5", "duration": 500 },
                { "note": "D5", "duration": 300 },
                { "note": "C5", "duration": 300 },
                { "note": "B4", "duration": 600 },
                { "note": "A4", "duration": 600 },

                { "note": "A2", "duration": 300 },
                { "note": "E3", "duration": 300 },
                { "note": "A3", "duration": 300 },
                { "note": "C4", "duration": 300 },

                { "note": "B4", "duration": 100 },
                { "note": "C5", "duration": 500 },
                { "note": "B4", "duration": 300 },
                { "note": "A4", "duration": 300 },
                { "note": "G4", "duration": 600 },
                { "note": "F4", "duration": 600 },

                { "note": "F2", "duration": 300 },
                { "note": "A2", "duration": 300 },
                { "note": "C3", "duration": 300 },
                { "note": "F3", "duration": 300 },

                { "note": "G4", "duration": 100 },
                { "note": "A4", "duration": 500 },
                { "note": "G4", "duration": 300 },
                { "note": "F4", "duration": 300 },
                { "note": "E4", "duration": 600 },
                { "note": "D4", "duration": 600 },

                { "note": "C2", "duration": 300 },
                { "note": "G2", "duration": 300 },
                { "note": "C3", "duration": 300 },
                { "note": "E3", "duration": 300 },

                { "note": "E4", "duration": 100 },
                { "note": "F4", "duration": 500 },
                { "note": "E4", "duration": 300 },
                { "note": "D4", "duration": 300 },
                { "note": "C4", "duration": 1200 },

                { "note": "G2", "duration": 300 },
                { "note": "B2", "duration": 300 },
                { "note": "D3", "duration": 300 },
                { "note": "G3", "duration": 300 },

                { "note": "G5", "duration": 800 },
                { "note": "F5", "duration": 400 },
                { "note": "E5", "duration": 400 },
                { "note": "D5", "duration": 800 },
                { "note": "C5", "duration": 800 },

                { "note": "A2", "duration": 400 },
                { "note": "E3", "duration": 400 },
                { "note": "A3", "duration": 400 },
                { "note": "C4", "duration": 400 },

                { "note": "F5", "duration": 800 },
                { "note": "E5", "duration": 400 },
                { "note": "D5", "duration": 400 },
                { "note": "C5", "duration": 800 },
                { "note": "B4", "duration": 800 },

                { "note": "F2", "duration": 400 },
                { "note": "A2", "duration": 400 },
                { "note": "C3", "duration": 400 },
                { "note": "F3", "duration": 400 },

                { "note": "E5", "duration": 800 },
                { "note": "D5", "duration": 400 },
                { "note": "C5", "duration": 400 },
                { "note": "B4", "duration": 800 },
                { "note": "A4", "duration": 800 },

                { "note": "C2", "duration": 400 },
                { "note": "G2", "duration": 400 },
                { "note": "C3", "duration": 400 },
                { "note": "E3", "duration": 400 },

                { "note": "D5", "duration": 800 },
                { "note": "C5", "duration": 400 },
                { "note": "B4", "duration": 400 },
                { "note": "A4", "duration": 1600 },

                { "note": "G2", "duration": 400 },
                { "note": "B2", "duration": 400 },
                { "note": "D3", "duration": 400 },
                { "note": "G3", "duration": 400 },

                { "note": "A3", "duration": 300 },
                { "note": "C4", "duration": 300 },
                { "note": "E4", "duration": 300 },
                { "note": "A4", "duration": 300 },
                { "note": "C5", "duration": 300 },
                { "note": "E5", "duration": 300 },
                { "note": "A5", "duration": 600 },

                { "note": "F3", "duration": 300 },
                { "note": "A3", "duration": 300 },
                { "note": "C4", "duration": 300 },
                { "note": "F4", "duration": 300 },
                { "note": "A4", "duration": 300 },
                { "note": "C5", "duration": 300 },
                { "note": "F5", "duration": 600 },

                { "note": "C3", "duration": 300 },
                { "note": "E3", "duration": 300 },
                { "note": "G3", "duration": 300 },
                { "note": "C4", "duration": 300 },
                { "note": "E4", "duration": 300 },
                { "note": "G4", "duration": 300 },
                { "note": "C5", "duration": 600 },

                { "note": "G3", "duration": 300 },
                { "note": "B3", "duration": 300 },
                { "note": "D4", "duration": 300 },
                { "note": "G4", "duration": 300 },
                { "note": "B4", "duration": 300 },
                { "note": "D5", "duration": 300 },
                { "note": "G5", "duration": 600 },

                { "note": "E5", "duration": 400 },
                { "note": "F5", "duration": 100 },
                { "note": "E5", "duration": 100 },
                { "note": "D5", "duration": 200 },
                { "note": "C5", "duration": 200 },
                { "note": "B4", "duration": 400 },
                { "note": "C5", "duration": 100 },
                { "note": "B4", "duration": 100 },
                { "note": "A4", "duration": 400 },

                { "note": "A2", "duration": 200 },
                { "note": "E3", "duration": 200 },
                { "note": "A3", "duration": 200 },
                { "note": "C4", "duration": 200 },
                { "note": "E4", "duration": 200 },
                { "note": "A4", "duration": 200 },

                { "note": "C5", "duration": 400 },
                { "note": "D5", "duration": 100 },
                { "note": "C5", "duration": 100 },
                { "note": "B4", "duration": 200 },
                { "note": "A4", "duration": 200 },
                { "note": "G4", "duration": 400 },
                { "note": "A4", "duration": 100 },
                { "note": "G4", "duration": 100 },
                { "note": "F4", "duration": 400 },

                { "note": "F2", "duration": 200 },
                { "note": "A2", "duration": 200 },
                { "note": "C3", "duration": 200 },
                { "note": "F3", "duration": 200 },
                { "note": "A3", "duration": 200 },
                { "note": "C4", "duration": 200 },

                { "note": "A4", "duration": 400 },
                { "note": "B4", "duration": 100 },
                { "note": "A4", "duration": 100 },
                { "note": "G4", "duration": 200 },
                { "note": "F4", "duration": 200 },
                { "note": "E4", "duration": 400 },
                { "note": "F4", "duration": 100 },
                { "note": "E4", "duration": 100 },
                { "note": "D4", "duration": 400 },

                { "note": "C2", "duration": 200 },
                { "note": "G2", "duration": 200 },
                { "note": "C3", "duration": 200 },
                { "note": "E3", "duration": 200 },
                { "note": "G3", "duration": 200 },
                { "note": "C4", "duration": 200 },

                { "note": "F4", "duration": 200 },
                { "note": "G4", "duration": 200 },
                { "note": "A4", "duration": 200 },
                { "note": "B4", "duration": 200 },
                { "note": "C5", "duration": 200 },
                { "note": "D5", "duration": 200 },
                { "note": "E5", "duration": 200 },
                { "note": "F5", "duration": 200 },
                { "note": "G5", "duration": 400 },

                { "note": "A5", "duration": 800 },
                { "note": "G5", "duration": 400 },
                { "note": "F5", "duration": 400 },
                { "note": "E5", "duration": 800 },
                { "note": "D5", "duration": 400 },
                { "note": "C5", "duration": 400 },
                { "note": "B4", "duration": 800 },
                { "note": "A4", "duration": 1200 },

                { "note": "G2", "duration": 200 },
                { "note": "B2", "duration": 200 },
                { "note": "D3", "duration": 200 },
                { "note": "G3", "duration": 200 },
                { "note": "B3", "duration": 200 },
                { "note": "D4", "duration": 200 },

                { "note": "A3", "duration": 500 },
                { "note": "C4", "duration": 500 },
                { "note": "E4", "duration": 500 },
                { "note": "A4", "duration": 500 },
                { "note": "C5", "duration": 1000 },

                { "note": "F3", "duration": 500 },
                { "note": "A3", "duration": 500 },
                { "note": "C4", "duration": 500 },
                { "note": "F4", "duration": 500 },
                { "note": "A4", "duration": 1000 },

                { "note": "C3", "duration": 500 },
                { "note": "E3", "duration": 500 },
                { "note": "G3", "duration": 500 },
                { "note": "C4", "duration": 500 },
                { "note": "E4", "duration": 1000 },

                { "note": "A2", "duration": 600 },
                { "note": "E3", "duration": 600 },
                { "note": "A3", "duration": 600 },
                { "note": "C4", "duration": 600 },
                { "note": "E4", "duration": 600 },
                { "note": "A4", "duration": 600 },
                { "note": "C5", "duration": 600 },
                { "note": "E5", "duration": 600 },
                { "note": "A5", "duration": 2400 }
            ]
        },
        {
            "name": "Storm of street",
            "notes": [
                { "note": "C2", "duration": 500 },
                { "note": "G2", "duration": 500 },
                { "note": "C3", "duration": 500 },
                { "note": "Eb3", "duration": 500 },
                { "note": "G3", "duration": 500 },

                { "note": "C4", "duration": 250 },
                { "note": "C5", "duration": 250 },
                { "note": "Bb4", "duration": 250 },
                { "note": "G4", "duration": 250 },
                { "note": "F4", "duration": 250 },
                { "note": "Eb4", "duration": 250 },
                { "note": "F4", "duration": 250 },
                { "note": "G4", "duration": 250 },

                { "note": "C4", "duration": 250 },
                { "note": "C5", "duration": 250 },
                { "note": "Bb4", "duration": 250 },
                { "note": "G4", "duration": 250 },
                { "note": "F4", "duration": 250 },
                { "note": "Eb4", "duration": 250 },
                { "note": "C4", "duration": 500 },

                { "note": "F3", "duration": 250 },
                { "note": "A3", "duration": 250 },
                { "note": "C4", "duration": 250 },
                { "note": "F4", "duration": 250 },

                { "note": "G3", "duration": 250 },
                { "note": "Bb3", "duration": 250 },
                { "note": "D4", "duration": 250 },
                { "note": "G4", "duration": 250 },

                { "note": "Ab3", "duration": 250 },
                { "note": "C4", "duration": 250 },
                { "note": "Eb4", "duration": 250 },
                { "note": "Ab4", "duration": 250 },

                { "note": "Bb3", "duration": 250 },
                { "note": "D4", "duration": 250 },
                { "note": "F4", "duration": 250 },
                { "note": "Bb4", "duration": 250 },

                { "note": "C3", "duration": 150 },
                { "note": "E3", "duration": 150 },
                { "note": "G3", "duration": 150 },
                { "note": "C4", "duration": 150 },
                { "note": "E4", "duration": 150 },
                { "note": "G4", "duration": 150 },
                { "note": "C5", "duration": 150 },
                { "note": "E5", "duration": 150 },

                { "note": "Bb2", "duration": 150 },
                { "note": "D3", "duration": 150 },
                { "note": "F3", "duration": 150 },
                { "note": "Bb3", "duration": 150 },
                { "note": "D4", "duration": 150 },
                { "note": "F4", "duration": 150 },
                { "note": "Bb4", "duration": 150 },
                { "note": "D5", "duration": 150 },

                { "note": "C3", "duration": 250 },
                { "note": "G3", "duration": 250 },
                { "note": "C4", "duration": 250 },
                { "note": "E4", "duration": 250 },
                { "note": "G4", "duration": 500 },

                { "note": "C3", "duration": 1000 },
                { "note": "G3", "duration": 1000 },
                { "note": "C4", "duration": 1000 }
            ]
        },
        {
            "name": "Legendary Victory",
            "notes": [
                { "note": "Ab3", "duration": 400 },
                { "note": "Eb4", "duration": 400 },
                { "note": "Gb4", "duration": 800 },
                { "note": "Db4", "duration": 400 },
                { "note": "F4", "duration": 400 },
                { "note": "Ab4", "duration": 800 },

                { "note": "Bb2", "duration": 100 }, { "note": "F3", "duration": 100 }, { "note": "Bb3", "duration": 100 }, { "note": "D4", "duration": 100 },
                { "note": "F4", "duration": 100 }, { "note": "Bb4", "duration": 100 }, { "note": "D5", "duration": 100 }, { "note": "F5", "duration": 100 },

                { "note": "C5", "duration": 150 }, { "note": "D5", "duration": 150 }, { "note": "Eb5", "duration": 300 },
                { "note": "F5", "duration": 150 }, { "note": "G5", "duration": 150 }, { "note": "Ab5", "duration": 600 },
                { "note": "Bb4", "duration": 150 }, { "note": "C5", "duration": 150 }, { "note": "D5", "duration": 300 },
                { "note": "Eb5", "duration": 150 }, { "note": "F5", "duration": 150 }, { "note": "G5", "duration": 600 },

                { "note": "Bb1", "duration": 300 }, { "note": "Bb2", "duration": 300 },
                { "note": "F2", "duration": 300 }, { "note": "F3", "duration": 300 },
                { "note": "Eb2", "duration": 300 }, { "note": "Eb3", "duration": 300 },
                { "note": "Bb2", "duration": 300 }, { "note": "Bb3", "duration": 300 },

                { "note": "Ab5", "duration": 80 }, { "note": "A5", "duration": 80 }, { "note": "Bb5", "duration": 80 }, { "note": "B5", "duration": 80 },
                { "note": "C6", "duration": 80 }, { "note": "Db6", "duration": 80 }, { "note": "D6", "duration": 80 }, { "note": "Eb6", "duration": 80 },
                { "note": "E6", "duration": 80 }, { "note": "F6", "duration": 80 }, { "note": "Gb6", "duration": 80 }, { "note": "G6", "duration": 160 },

                { "note": "Ab1", "duration": 80 }, { "note": "A1", "duration": 80 }, { "note": "Bb1", "duration": 80 }, { "note": "B1", "duration": 80 },
                { "note": "C2", "duration": 80 }, { "note": "Db2", "duration": 80 }, { "note": "D2", "duration": 80 }, { "note": "Eb2", "duration": 160 },

                { "note": "Eb3", "duration": 200 }, { "note": "Bb3", "duration": 200 }, { "note": "Eb4", "duration": 200 }, { "note": "G4", "duration": 200 },
                { "note": "F3", "duration": 200 }, { "note": "C4", "duration": 200 }, { "note": "F4", "duration": 200 }, { "note": "A4", "duration": 200 },
                { "note": "Gb3", "duration": 200 }, { "note": "Db4", "duration": 200 }, { "note": "Gb4", "duration": 200 }, { "note": "Bb4", "duration": 200 },
                { "note": "G3", "duration": 200 }, { "note": "D4", "duration": 200 }, { "note": "G4", "duration": 200 }, { "note": "B4", "duration": 400 },

                { "note": "C5", "duration": 400 }, { "note": "Eb5", "duration": 200 }, { "note": "D5", "duration": 200 }, { "note": "Bb4", "duration": 400 },
                { "note": "Ab4", "duration": 800 },
                { "note": "Bb4", "duration": 200 }, { "note": "C5", "duration": 200 }, { "note": "D5", "duration": 200 }, { "note": "Eb5", "duration": 200 },
                { "note": "F5", "duration": 800 },

                { "note": "Ab3", "duration": 50 }, { "note": "Eb4", "duration": 50 }, { "note": "Ab4", "duration": 50 }, { "note": "C5", "duration": 50 },
                { "note": "Eb5", "duration": 50 }, { "note": "C5", "duration": 50 }, { "note": "Ab4", "duration": 50 }, { "note": "Eb4", "duration": 50 },
                { "note": "Bb3", "duration": 50 }, { "note": "F4", "duration": 50 }, { "note": "Bb4", "duration": 50 }, { "note": "D5", "duration": 50 },
                { "note": "F5", "duration": 50 }, { "note": "D5", "duration": 50 }, { "note": "Bb4", "duration": 50 }, { "note": "F4", "duration": 50 },

                { "note": "C5", "duration": 100 }, { "note": "Eb5", "duration": 100 }, { "note": "G5", "duration": 100 },
                { "note": "Bb5", "duration": 100 }, { "note": "C6", "duration": 100 }, { "note": "Eb6", "duration": 100 },
                { "note": "G6", "duration": 100 }, { "note": "Bb6", "duration": 100 }, { "note": "C7", "duration": 400 },

                { "note": "Bb6", "duration": 50 }, { "note": "Ab6", "duration": 50 }, { "note": "G6", "duration": 50 }, { "note": "F6", "duration": 50 },
                { "note": "Eb6", "duration": 50 }, { "note": "D6", "duration": 50 }, { "note": "C6", "duration": 50 }, { "note": "Bb5", "duration": 50 },
                { "note": "Ab5", "duration": 50 }, { "note": "G5", "duration": 50 }, { "note": "F5", "duration": 50 }, { "note": "Eb5", "duration": 50 },
                { "note": "D5", "duration": 50 }, { "note": "C5", "duration": 50 }, { "note": "Bb4", "duration": 50 }, { "note": "Ab4", "duration": 50 },

                { "note": "Eb3", "duration": 200 }, { "note": "Bb3", "duration": 200 }, { "note": "Eb4", "duration": 200 }, { "note": "G4", "duration": 200 },
                { "note": "Bb4", "duration": 200 }, { "note": "Eb5", "duration": 200 }, { "note": "G5", "duration": 200 }, { "note": "Bb5", "duration": 800 },

                { "note": "Eb2", "duration": 100 }, { "note": "Eb3", "duration": 100 }, { "note": "Bb3", "duration": 100 }, { "note": "Eb4", "duration": 100 },
                { "note": "G4", "duration": 100 }, { "note": "Bb4", "duration": 100 }, { "note": "Eb5", "duration": 100 }, { "note": "G5", "duration": 100 },
                { "note": "Bb5", "duration": 100 }, { "note": "Eb6", "duration": 100 }, { "note": "G6", "duration": 100 }, { "note": "Bb6", "duration": 1600 }
            ]
        },
        {
            "name": "bacteria - YYHJ",
            "notes": [
                { "note": "E4", "duration": 300 },
                { "note": "A4", "duration": 300 },
                { "note": "B4", "duration": 300 },
                { "note": "C5", "duration": 300 },
                { "note": "D5", "duration": 300 },
                { "note": "B4", "duration": 300 },
                { "note": "C5", "duration": 300 },
                { "note": "A4", "duration": 300 },

                { "note": "A4", "duration": 300 },
                { "note": "G4", "duration": 150 },
                { "note": "A4", "duration": 150 },
                { "note": "B4", "duration": 300 },
                { "note": "C5", "duration": 150 },
                { "note": "D5", "duration": 150 },
                { "note": "E5", "duration": 300 },
                { "note": "E5", "duration": 150 }, { "note": "E5", "duration": 150 }, { "note": "E5", "duration": 300 },

                { "note": "E5", "duration": 300 }, { "note": "D5", "duration": 300 }, { "note": "E5", "duration": 150 }, { "note": "F5", "duration": 150 },

                { "note": "C5", "duration": 150 }, { "note": "D5", "duration": 150 }, { "note": "E5", "duration": 300 },
                { "note": "B4", "duration": 300 }, { "note": "A4", "duration": 150 }, { "note": "A4", "duration": 150 }, { "note": "B4", "duration": 300 },

                { "note": "D5", "duration": 300 }, { "note": "B4", "duration": 300 }, { "note": "C5", "duration": 300 },
                { "note": "A4", "duration": 300 }, { "note": "E5", "duration": 300 },

                { "note": "C5", "duration": 300 }, { "note": "D5", "duration": 300 }, { "note": "B4", "duration": 300 },
                { "note": "C5", "duration": 300 }, { "note": "A4", "duration": 300 },

                { "note": "A4", "duration": 300 }, { "note": "G4", "duration": 150 }, { "note": "A4", "duration": 150 }, { "note": "B4", "duration": 300 },
                { "note": "C5", "duration": 150 }, { "note": "D5", "duration": 150 }, { "note": "E5", "duration": 300 },

                { "note": "E5", "duration": 150 }, { "note": "E5", "duration": 150 }, { "note": "E5", "duration": 300 },
                { "note": "B4", "duration": 300 },

                { "note": "C5", "duration": 150 }, { "note": "D5", "duration": 150 }, { "note": "E5", "duration": 300 },
                { "note": "A4", "duration": 150 }, { "note": "A4", "duration": 150 }, { "note": "B4", "duration": 300 },


                { "note": "D5", "duration": 300 }, { "note": "A4", "duration": 300 }, { "note": "E5", "duration": 150 }, { "note": "A5", "duration": 150 },


                { "note": "C5", "duration": 300 }, { "note": "D5", "duration": 300 }, { "note": "B4", "duration": 300 },
                { "note": "A4", "duration": 300 },


                { "note": "A4", "duration": 150 }, { "note": "G4", "duration": 150 }, { "note": "A4", "duration": 150 }, { "note": "B4", "duration": 150 },
                { "note": "E5", "duration": 150 }, { "note": "D5", "duration": 150 }, { "note": "E5", "duration": 150 }, { "note": "B4", "duration": 150 },
                { "note": "E5", "duration": 150 }, { "note": "D5", "duration": 150 }, { "note": "D5", "duration": 150 },


                { "note": "C5", "duration": 300 }, { "note": "B4", "duration": 150 }, { "note": "A4", "duration": 150 }, { "note": "B4", "duration": 300 },
                { "note": "A4", "duration": 150 }, { "note": "B4", "duration": 150 }, { "note": "G4", "duration": 150 }, { "note": "F4", "duration": 150 },
                { "note": "G4", "duration": 150 }, { "note": "B4", "duration": 150 }, { "note": "G4", "duration": 150 },


                { "note": "G4", "duration": 150 }, { "note": "F4", "duration": 150 }, { "note": "F4", "duration": 150 }, { "note": "E4", "duration": 150 },
                { "note": "D4", "duration": 150 }, { "note": "C4", "duration": 150 }, { "note": "C4", "duration": 150 }, { "note": "D4", "duration": 150 },
                { "note": "E4", "duration": 150 }, { "note": "C4", "duration": 150 }, { "note": "C4", "duration": 300 },


                { "note": "E5", "duration": 150 }, { "note": "A5", "duration": 150 }, { "note": "G5", "duration": 150 }, { "note": "F5", "duration": 150 },
                { "note": "E5", "duration": 150 }, { "note": "D5", "duration": 150 }, { "note": "C5", "duration": 150 }, { "note": "D5", "duration": 150 },


                { "note": "A4", "duration": 300 }, { "note": "G4", "duration": 150 }, { "note": "A4", "duration": 150 },


                { "note": "D5", "duration": 300 }, { "note": "D5", "duration": 150 }, { "note": "F5", "duration": 150 },
                { "note": "D5", "duration": 300 }, { "note": "B4", "duration": 150 }, { "note": "A4", "duration": 150 },
                { "note": "A4", "duration": 150 }, { "note": "D5", "duration": 150 }, { "note": "A4", "duration": 150 }, { "note": "G4", "duration": 150 },
                { "note": "B4", "duration": 300 },


                { "note": "A4", "duration": 150 }, { "note": "G4", "duration": 150 }, { "note": "A4", "duration": 150 }, { "note": "B4", "duration": 150 },
                { "note": "E5", "duration": 300 },
                { "note": "A4", "duration": 150 }, { "note": "B4", "duration": 150 }, { "note": "G4", "duration": 150 }, { "note": "B4", "duration": 150 },


                { "note": "F5", "duration": 150 }, { "note": "E5", "duration": 150 }, { "note": "D5", "duration": 150 }, { "note": "E5", "duration": 150 },
                { "note": "D5", "duration": 150 }, { "note": "C5", "duration": 150 }, { "note": "C5", "duration": 150 }, { "note": "D5", "duration": 150 },
                { "note": "C5", "duration": 150 }, { "note": "A4", "duration": 300 }, { "note": "G5", "duration": 150 },


                { "note": "A5", "duration": 150 }, { "note": "G5", "duration": 150 }, { "note": "A5", "duration": 150 }, { "note": "E5", "duration": 150 },
                { "note": "A5", "duration": 150 }, { "note": "G5", "duration": 150 }, { "note": "A5", "duration": 150 }, { "note": "F5", "duration": 150 },
                { "note": "A5", "duration": 150 }, { "note": "E5", "duration": 150 }, { "note": "A5", "duration": 150 }, { "note": "D5", "duration": 300 },


                { "note": "C6", "duration": 300 },
                { "note": "D5", "duration": 300 }, { "note": "D5", "duration": 150 }, { "note": "B4", "duration": 150 },
                { "note": "B4", "duration": 300 },
                { "note": "D5", "duration": 150 }, { "note": "E5", "duration": 150 }, { "note": "F5", "duration": 150 }, { "note": "G5", "duration": 150 },


                { "note": "F5", "duration": 150 }, { "note": "E5", "duration": 150 }, { "note": "D5", "duration": 300 },
                { "note": "E5", "duration": 150 }, { "note": "A5", "duration": 150 }, { "note": "B5", "duration": 300 },


                { "note": "D5", "duration": 300 }, { "note": "B4", "duration": 150 }, { "note": "A4", "duration": 150 },
                { "note": "A4", "duration": 150 }, { "note": "G4", "duration": 150 }, { "note": "A4", "duration": 150 }, { "note": "B4", "duration": 150 },
                { "note": "C5", "duration": 150 }, { "note": "D5", "duration": 150 },


                { "note": "E5", "duration": 150 }, { "note": "E5", "duration": 150 }, { "note": "E5", "duration": 150 }, { "note": "E5", "duration": 150 },
                { "note": "E5", "duration": 150 }, { "note": "E5", "duration": 150 }, { "note": "E5", "duration": 150 }, { "note": "E5", "duration": 150 },


                { "note": "D5", "duration": 150 }, { "note": "E5", "duration": 150 }, { "note": "F5", "duration": 300 },
                { "note": "C5", "duration": 150 }, { "note": "D5", "duration": 150 }, { "note": "E5", "duration": 300 },
                { "note": "B4", "duration": 300 },


                { "note": "A4", "duration": 150 }, { "note": "A4", "duration": 150 }, { "note": "B4", "duration": 300 },
                { "note": "C5", "duration": 300 }, { "note": "D5", "duration": 300 },


                { "note": "C5", "duration": 300 },
                { "note": "A4", "duration": 150 }, { "note": "E5", "duration": 150 }, { "note": "A5", "duration": 150 }, { "note": "B5", "duration": 150 },


                { "note": "C5", "duration": 300 }, { "note": "A4", "duration": 150 }, { "note": "G4", "duration": 150 }, { "note": "A4", "duration": 150 }, { "note": "B4", "duration": 150 },
                { "note": "C5", "duration": 150 }, { "note": "D5", "duration": 150 }, { "note": "E5", "duration": 300 },


                { "note": "E5", "duration": 150 }, { "note": "E5", "duration": 150 }, { "note": "E5", "duration": 150 }, { "note": "E5", "duration": 150 },
                { "note": "E5", "duration": 150 }, { "note": "E5", "duration": 150 }, { "note": "E5", "duration": 150 }, { "note": "E5", "duration": 150 },


                { "note": "D5", "duration": 150 }, { "note": "E5", "duration": 150 }, { "note": "F5", "duration": 300 },
                { "note": "C5", "duration": 150 }, { "note": "D5", "duration": 150 }, { "note": "E5", "duration": 300 },
                { "note": "B4", "duration": 300 },


                { "note": "A4", "duration": 150 }, { "note": "A4", "duration": 150 }, { "note": "B4", "duration": 300 },
                { "note": "C5", "duration": 300 }, { "note": "D5", "duration": 300 }, { "note": "C5", "duration": 300 },


                { "note": "A4", "duration": 150 }, { "note": "E5", "duration": 150 }, { "note": "A5", "duration": 150 }, { "note": "B5", "duration": 150 },
                { "note": "C5", "duration": 300 }, { "note": "D5", "duration": 300 },


                { "note": "C5", "duration": 300 },
                { "note": "A4", "duration": 150 }, { "note": "E5", "duration": 150 }, { "note": "A5", "duration": 150 }, { "note": "B5", "duration": 150 },


                { "note": "D5", "duration": 300 }, { "note": "C5", "duration": 300 },
                { "note": "B4", "duration": 150 }, { "note": "A4", "duration": 150 }, { "note": "A4", "duration": 150 }, { "note": "G4", "duration": 150 },
                { "note": "A4", "duration": 150 }, { "note": "B4", "duration": 150 },


                { "note": "E5", "duration": 150 }, { "note": "E5", "duration": 150 }, { "note": "E5", "duration": 150 }, { "note": "A5", "duration": 150 },
                { "note": "D5", "duration": 150 }, { "note": "E5", "duration": 150 }, { "note": "F5", "duration": 300 },


                { "note": "C5", "duration": 150 }, { "note": "D5", "duration": 150 }, { "note": "E5", "duration": 300 },
                { "note": "B4", "duration": 300 }, { "note": "A4", "duration": 150 }, { "note": "B4", "duration": 150 },


                { "note": "A4", "duration": 300 }, { "note": "A4", "duration": 150 }, { "note": "A4", "duration": 150 },


                { "note": "A4", "duration": 1200 }
            ]
        }
    ];
}